version: '3.9'
services:
  lufthansa_db:
    container_name: Lufthansa_db
    image: cespar/lufthansa_db:latest
    networks:
      - host
    ports:
      - 27017:27017

  fastapi:
    container_name: Lufthansa_api
    image: cespar/lufthansa_api:latest
    networks:
      - host
    ports:
      - 8000:8000
    depends_on:
      - "lufthansa_db"
  lufthansa_dash:
    container_name: lufthansa_dash
    image: cespar/lufthansa_dash:latest
    networks:
      - host
    ports:
      - 5000:5000
    depends_on:
      - "lufthansa_db"
networks:
  host:
